import { Land, BlogPost, Testimonial, TeamMember } from './types'

export const lands: Land[] = [
  {
    id: '1',
    title: 'Prestigious Beachfront Estate Plot',
    slug: 'prestigious-beachfront-estate-plot',
    location: 'Grand Baie',
    region: 'North',
    price: 45000000,
    currency: 'MUR',
    size: 2500,
    sizeUnit: 'm²',
    pricePerUnit: 18000,
    description: 'An exceptional beachfront plot offering unparalleled views of the Indian Ocean. This premium land parcel is ideally positioned within an exclusive gated community, featuring direct beach access and world-class amenities. Perfect for building your dream luxury residence or as a prestigious investment opportunity.',
    shortDescription: 'Exceptional beachfront plot with panoramic ocean views in an exclusive gated community.',
    features: ['Beachfront', 'Gated Community', 'Ocean Views', 'Direct Beach Access'],
    amenities: ['24/7 Security', 'Private Beach', 'Tennis Courts', 'Helipad Access'],
    investmentHighlights: ['15% annual appreciation', 'Foreign ownership allowed', 'IRS Scheme eligible', 'Rental income potential'],
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1920&q=80',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1920&q=80',
      'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1920&q=80',
    ],
    coordinates: { lat: -20.0107, lng: 57.5799 },
    status: 'available',
    type: 'residential',
    isFeatured: true,
    isNew: true,
    createdAt: '2024-01-15',
    updatedAt: '2024-01-20',
  },
  {
    id: '2',
    title: 'Hillside Panoramic View Estate',
    slug: 'hillside-panoramic-view-estate',
    location: 'Tamarin',
    region: 'West',
    price: 32000000,
    currency: 'MUR',
    size: 3200,
    sizeUnit: 'm²',
    pricePerUnit: 10000,
    description: 'Nestled in the prestigious hills of Tamarin, this magnificent plot offers breathtaking 360-degree views of the mountains and ocean. The elevated position ensures privacy while providing spectacular sunsets over the Tamarin Bay.',
    shortDescription: 'Magnificent hillside plot with 360-degree mountain and ocean views.',
    features: ['Mountain Views', 'Ocean Views', 'Elevated Position', 'Privacy'],
    amenities: ['Underground Utilities', 'Paved Roads', 'Security Patrol'],
    investmentHighlights: ['12% annual appreciation', 'Prime location', 'Limited availability', 'PDS Scheme eligible'],
    images: [
      'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=1920&q=80',
      'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1920&q=80',
      'https://images.unsplash.com/photo-1472214103451-9374bd1c798e?w=1920&q=80',
    ],
    coordinates: { lat: -20.3254, lng: 57.3820 },
    status: 'available',
    type: 'residential',
    isFeatured: true,
    isNew: false,
    createdAt: '2024-01-10',
    updatedAt: '2024-01-18',
  },
  {
    id: '3',
    title: 'Golf Course Premium Land',
    slug: 'golf-course-premium-land',
    location: 'Bel Ombre',
    region: 'South',
    price: 28500000,
    currency: 'MUR',
    size: 1800,
    sizeUnit: 'm²',
    pricePerUnit: 15833,
    description: 'A rare opportunity to acquire prime land adjacent to a championship golf course in the prestigious Bel Ombre estate. This exclusive plot offers serene surroundings, lush tropical landscaping, and access to world-class resort amenities.',
    shortDescription: 'Prime land adjacent to championship golf course with resort amenities.',
    features: ['Golf Course Frontage', 'Resort Access', 'Tropical Gardens', 'Quiet Location'],
    amenities: ['Golf Club Membership', 'Spa Access', 'Beach Club', 'Restaurant'],
    investmentHighlights: ['Stable appreciation', 'Resort community', 'High rental demand', 'IRS eligible'],
    images: [
      'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=1920&q=80',
      'https://images.unsplash.com/photo-1587171252505-6bcc1eaa3f59?w=1920&q=80',
      'https://images.unsplash.com/photo-1536504296317-91cf84e54f7f?w=1920&q=80',
    ],
    coordinates: { lat: -20.4961, lng: 57.3952 },
    status: 'available',
    type: 'residential',
    isFeatured: true,
    isNew: false,
    createdAt: '2024-01-05',
    updatedAt: '2024-01-15',
  },
  {
    id: '4',
    title: 'Coastal Investment Parcel',
    slug: 'coastal-investment-parcel',
    location: 'Pointe aux Canonniers',
    region: 'North',
    price: 52000000,
    currency: 'MUR',
    size: 4000,
    sizeUnit: 'm²',
    pricePerUnit: 13000,
    description: 'Prime coastal land in the sought-after Pointe aux Canonniers area. This expansive plot offers exceptional development potential with stunning ocean views and proximity to Grand Baie amenities.',
    shortDescription: 'Expansive coastal land with exceptional development potential.',
    features: ['Coastal Location', 'Development Potential', 'Near Grand Baie', 'Ocean Proximity'],
    amenities: ['Public Beach Access', 'Shopping Nearby', 'Restaurants'],
    investmentHighlights: ['High development value', '18% ROI potential', 'Growing area', 'Tourist hotspot'],
    images: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1920&q=80',
      'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=1920&q=80',
      'https://images.unsplash.com/photo-1509233725247-49e657c54213?w=1920&q=80',
    ],
    coordinates: { lat: -20.0245, lng: 57.6021 },
    status: 'available',
    type: 'mixed-use',
    isFeatured: false,
    isNew: true,
    createdAt: '2024-01-20',
    updatedAt: '2024-01-20',
  },
  {
    id: '5',
    title: 'Mountain Retreat Estate',
    slug: 'mountain-retreat-estate',
    location: 'Chamarel',
    region: 'South-West',
    price: 18500000,
    currency: 'MUR',
    size: 5500,
    sizeUnit: 'm²',
    pricePerUnit: 3364,
    description: 'Escape to paradise with this magnificent mountain estate in Chamarel. Surrounded by lush tropical forests and offering views of the famous Chamarel waterfalls, this is the perfect retreat from urban life.',
    shortDescription: 'Magnificent mountain estate surrounded by tropical forests.',
    features: ['Mountain Setting', 'Forest Views', 'Waterfall Views', 'Large Plot'],
    amenities: ['Natural Springs', 'Hiking Trails', 'Nature Reserve'],
    investmentHighlights: ['Eco-tourism potential', 'Unique location', 'Agricultural rights', 'Growing eco-market'],
    images: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1920&q=80',
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1920&q=80',
      'https://images.unsplash.com/photo-1486870591958-9b9d0d1dda99?w=1920&q=80',
    ],
    coordinates: { lat: -20.4359, lng: 57.3809 },
    status: 'available',
    type: 'residential',
    isFeatured: false,
    isNew: false,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-10',
  },
  {
    id: '6',
    title: 'Marina Development Site',
    slug: 'marina-development-site',
    location: 'Black River',
    region: 'West',
    price: 75000000,
    currency: 'MUR',
    size: 8000,
    sizeUnit: 'm²',
    pricePerUnit: 9375,
    description: 'Exceptional waterfront development opportunity in Black River. This prime marina-front site offers unmatched potential for luxury residential or boutique hotel development with direct water access.',
    shortDescription: 'Prime marina-front development site with direct water access.',
    features: ['Marina Access', 'Waterfront', 'Development Ready', 'Central Location'],
    amenities: ['Marina Berths', 'Boat Launch', 'Fish Market', 'Restaurants'],
    investmentHighlights: ['Development permit ready', 'High-value location', 'Tourism growth', 'Unique opportunity'],
    images: [
      'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=1920&q=80',
      'https://images.unsplash.com/photo-1502933691298-84fc14542831?w=1920&q=80',
      'https://images.unsplash.com/photo-1504681869696-d977211a5f4c?w=1920&q=80',
    ],
    coordinates: { lat: -20.3702, lng: 57.3718 },
    status: 'reserved',
    type: 'commercial',
    isFeatured: true,
    isNew: false,
    createdAt: '2023-12-20',
    updatedAt: '2024-01-05',
  },
]

export const blogPosts: BlogPost[] = [
  {
    id: '1',
    title: 'Why Mauritius is the Premier Destination for Land Investment in 2024',
    slug: 'mauritius-premier-destination-land-investment-2024',
    excerpt: 'Discover why savvy investors are choosing Mauritius for their next land investment and what makes this island nation a hotspot for premium real estate.',
    content: 'Full article content here...',
    image: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=1920&q=80',
    author: {
      name: 'Alexandra Chen',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80',
      role: 'Investment Analyst',
    },
    category: 'Investment',
    tags: ['Investment', 'Mauritius', 'Real Estate', '2024 Trends'],
    publishedAt: '2024-01-15',
    readTime: 8,
  },
  {
    id: '2',
    title: 'Understanding the IRS and PDS Schemes for Foreign Investors',
    slug: 'understanding-irs-pds-schemes-foreign-investors',
    excerpt: 'A comprehensive guide to the Integrated Resort Scheme (IRS) and Property Development Scheme (PDS) for international buyers looking to invest in Mauritius.',
    content: 'Full article content here...',
    image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1920&q=80',
    author: {
      name: 'James Morrison',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80',
      role: 'Legal Advisor',
    },
    category: 'Legal',
    tags: ['IRS', 'PDS', 'Foreign Investment', 'Legal Guide'],
    publishedAt: '2024-01-10',
    readTime: 12,
  },
  {
    id: '3',
    title: 'Top 5 Regions in Mauritius for Premium Land Acquisition',
    slug: 'top-5-regions-mauritius-premium-land-acquisition',
    excerpt: 'Explore the most prestigious regions in Mauritius offering exceptional land investment opportunities with high growth potential.',
    content: 'Full article content here...',
    image: 'https://images.unsplash.com/photo-1596005554384-d293674c91d7?w=1920&q=80',
    author: {
      name: 'Sophie Laurent',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80',
      role: 'Market Research',
    },
    category: 'Market Analysis',
    tags: ['Regions', 'Investment Zones', 'Market Analysis'],
    publishedAt: '2024-01-05',
    readTime: 10,
  },
]

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Michael Thompson',
    role: 'Property Investor',
    company: 'Thompson Holdings',
    content: 'Versate made our land investment journey seamless. Their expertise in the Mauritius market and attention to detail exceeded all expectations. We secured a prime beachfront plot that has already appreciated 20%.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80',
    rating: 5,
  },
  {
    id: '2',
    name: 'Elena Rodriguez',
    role: 'CEO',
    company: 'Global Ventures Ltd',
    content: 'The level of professionalism and market knowledge demonstrated by the Versate team is unmatched. They guided us through the entire process, from selection to closing, with impeccable service.',
    avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=200&q=80',
    rating: 5,
  },
  {
    id: '3',
    name: 'David Chen',
    role: 'Portfolio Manager',
    company: 'Asian Capital Partners',
    content: 'Outstanding service from start to finish. Versate understands the luxury market and delivered exactly what we were looking for. Their exclusive listings are truly premium quality.',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80',
    rating: 5,
  },
]

export const teamMembers: TeamMember[] = [
  {
    id: '1',
    name: 'Alexandre Dupont',
    role: 'Founder & CEO',
    bio: 'With over 20 years in luxury real estate, Alexandre founded Versate to bring world-class investment opportunities to discerning clients.',
    image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&q=80',
    social: {
      linkedin: '#',
      email: 'alexandre@versate.mu',
    },
  },
  {
    id: '2',
    name: 'Marie-Claire Beaumont',
    role: 'Head of Sales',
    bio: 'Marie-Claire brings exceptional expertise in high-value land transactions and has facilitated over $200M in successful deals.',
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&q=80',
    social: {
      linkedin: '#',
      email: 'marie@versate.mu',
    },
  },
  {
    id: '3',
    name: 'Jean-Pierre Martin',
    role: 'Investment Director',
    bio: 'Jean-Pierre specializes in identifying premium investment opportunities and advising international clients on portfolio diversification.',
    image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&q=80',
    social: {
      linkedin: '#',
      email: 'jeanpierre@versate.mu',
    },
  },
  {
    id: '4',
    name: 'Isabella Rossi',
    role: 'Client Relations Manager',
    bio: 'Isabella ensures every client receives personalized attention and a seamless experience throughout their investment journey.',
    image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&q=80',
    social: {
      linkedin: '#',
      email: 'isabella@versate.mu',
    },
  },
]

export const stats = [
  { label: 'Properties Sold', value: '500+', suffix: '' },
  { label: 'Total Investment Value', value: '2.5', suffix: 'B MUR' },
  { label: 'Happy Clients', value: '350+', suffix: '' },
  { label: 'Years of Excellence', value: '15', suffix: '+' },
]

export const regions = [
  { value: 'north', label: 'North' },
  { value: 'south', label: 'South' },
  { value: 'east', label: 'East' },
  { value: 'west', label: 'West' },
  { value: 'south-west', label: 'South-West' },
]

export const propertyTypes = [
  { value: 'residential', label: 'Residential' },
  { value: 'commercial', label: 'Commercial' },
  { value: 'mixed-use', label: 'Mixed-Use' },
  { value: 'agricultural', label: 'Agricultural' },
]
